### ISSUE TITLE
Publish multiarch Docker image

### ISSUE THREAD

**Issue by VladRassokhin** [ivarref/mikkmokk-proxy#1]
Please publish arm64 version of docker image.

Use e.g. (tried locally):
```
# uncomment following line if you don't have 'docker-container'-based driver yet, check with `docker buildx ls`. 'docker' driver cannot build multiarch images.
# docker buildx create --name multiarch --driver docker-container --use

docker buildx build --platform linux/arm64,linux/amd64 --tag "docker.io/ivarref/mikkmokk-proxy:$VERSION"  .
```

Also probably worth bumping Docker dependencies :)

Also maybe worth publishing jars to GitHub releases?

Nice tool, BTW 👍

**Comment by ivarref** [comment]
Released `docker.io/ivarref/mikkmokk-proxy:v0.1.63` now, can you confirm it works @VladRassokhin ?

Thanks!

**Comment by VladRassokhin** [comment]
Works flawlessly, thank you!
